USE ADVENTUREWORKSLT
GO

-- DISPLAY THE SALES ORDER DETAILS FOR ITEMS THAT ARE EQUAL TO THE MAXIMUM UNIT PRICE FOR THAT SALES ORDER

SELECT SOH.SalesOrderID, MUP.MaxUnitPrice
FROM SalesLT.SalesOrderHeader AS SOH
CROSS APPLY SalesLT.udfMaxUnitPrice(SOH.SalesOrderID) AS MUP
ORDER BY SOH.SalesOrderID;