USE ADVENTUREWORKSLt
GO

-- CREATE A STORE PROCEDURE
CREATE PROCEDURE SalesLT.GetProductByCategory (@CategoryID INT = NULL) -- NOMBRE PARAMETRO EN ESQUEMA SALESLT CON PARAMETRO DE ENTRADA ENTERO @CATEGORY  Y VALOR NULL POR DEFECTO
AS
IF @CategoryID IS NULL
	SELECT ProductID, Name, Color, Size, ListPrice
	FROM SalesLT.Product
ELSE
	SELECT ProductID, Name, Color, Size, ListPrice
	FROM SalesLT.Product
	WHERE ProductCategoryID = @CategoryID

-- EXECUTE THE PROCEDURE WITHOUT A PARAMETER
EXEC SalesLT.GetProductByCategory;

-- EXECUTE THE PROCEDURE WITH A PARAMETER
EXEC SalesLT.GetProductByCategory 6;
	