use adventureworkslt
go

-- LIST INFOMRATION ABOUT THE COLOR WITH PRODUCTMODELID 6
SELECT Name, Color, Size FROM SalesLT.Product
WHERE ProductModelID = 6;

-- LIST INFOMRATION ABOUT THE COLOR WITH PRODUCTMODELID > 6
SELECT Name, Color, Size FROM SalesLT.Product
WHERE ProductModelID > 6;

-- LIST INFOMRATION ABOUT THE COLOR WITH PRODUCTMODELID DIFFERENT <> 6
SELECT Name, Color, Size FROM SalesLT.Product
WHERE ProductModelID <> 6;

-- LIST INFORMATION ABOUT PRODUCTS THAT HAVE A PRODUCT NUMBER BEGINING FR
SELECT ProductNumber, Name, ListPrice 
FROM SalesLT.Product WHERE ProductNumber LIKE 'FR%';


-- LIST INFORMATION ABOUT PRODUCTS THAT HAVE A PRODUCT NUMBER ENDING IN 58
SELECT ProductNumber, Name, ListPrice 
FROM SalesLT.Product WHERE ProductNumber LIKE '%58';

-- LIST INFORMATION ABOUT PRODUCTS THAT HAVE A PRODUCT NUMBER THAT COINTAINS R 
SELECT ProductNumber, Name, ListPrice 
FROM SalesLT.Product WHERE ProductNumber LIKE '%R%';

-- FILTER THE PREVIOUS QUERY TO ENSURE THAT THE PRODUCT NUMBER CONTAINS TWO SETS OF TWO DIDGETS
SELECT Name, ProductNumber
FROM SalesLT.Product WHERE ProductNumber LIKE 'FR-_[0-9][0-9]_-[0-9][0-9]';

-- FIND PRODUCTS THAT HAVE NOT SELL END DATE
SELECT Name, SellEndDate FROM SalesLT.Product WHERE SellEndDate IS NOT NULL;

-- FIND PRODUCTS THAT HAVE A SELL END DATE IN 2006
SELECT Name, SellEndDate FROM SalesLT.Product WHERE SellEndDate BETWEEN '2006/01/01' AND '2006/12/31';

-- FIND PRODUCTS THAT HAVE A CATEGORY ID OF 5,6 OR 7
SELECT Name, ProductCategoryID FROM SalesLT.Product WHERE ProductCategoryID IN (5,6,7);

-- FIND PRODUCTS THAT HAVE A CATEGORY ID OF 5,6 OR 7 AND HAVE A SELL END DATE
SELECT Name, ProductCategoryID, SellEndDate FROM SalesLT.Product WHERE ProductCategoryID IN (5,6,7) AND SellEndDate IS NOT NULL;

-- SELECT PRODUCTS THAT HAVE A CATEGORY OF 5,6 OR 7 AND A PRODUCT NUMBER THAT BEGINS FR
SELECT Name, ProductCategoryID, ProductNumber FROM SalesLT.Product where ProductCategoryID IN (5,6,7) OR ProductNumber LIKE 'FR%';