use [AdventureWorksLT]
go

select *, 'Dato' AS type
from SalesLT.Employee;

-- UNION RETREIVE INFORMATION FROM MORE THAN 1 TABLE, IT HAS TO HAVE THE SAME COLUMNS
SELECT FirstName, LastName
FROM SalesLT.Employee
UNION
SELECT FirstName, LastName
FROM SalesLT.Customer
ORDER BY LastName;

-- UNION RETREIVE INFORMATION FROM MORE THAN 1 TABLE, IT HAS TO HAVE THE SAME COLUMNS
SELECT FirstName, LastName
FROM SalesLT.Employee
UNION ALL -- WHITH THE USE 'ALL', THE INFORMATION WILL BRING ALSO THE DUPLICATE VALUES
SELECT FirstName, LastName
FROM SalesLT.Customer
ORDER BY LastName;

-- INTERSECT WILL SHOW ONLY DE DATA THAT IS DUPLICATED IN BOTH TABLES
SELECT FirstName, LastName
FROM SalesLT.Employee
INTERSECT
SELECT FirstName, LastName
FROM SalesLT.Customer
ORDER BY LastName;

-- EXCEPT WILL SHOW ONLY DE DATA THAT APPEARS IN ONE TABLE BUT NOT IN ANOTHER ONE
SELECT FirstName, LastName
FROM SalesLT.Employee
EXCEPT
SELECT FirstName, LastName
FROM SalesLT.Customer
ORDER BY LastName;

